version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test: 
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lerna:bootstrap 

  build:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lerna:bootstrap 
            - run: yarn lerna:publish
workflows:
    build:
      jobs:
        - test
        - build:
            requires:
              - test
