version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test: 
     executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn bootstrap 

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn bootstrap 
            - run: yarn publish
workflows:
    build:
      jobs:
        - test
        - build:
            requires:
              - test
